#!/bin/bash
go test -v -mod=vendor ./...

if [ $? -ne 0 ]; then
  echo "go test fail" >&2
  exit 1
fi

go test -v -mod=vendor ./... -covermode=count -coverprofile=coverage.out

if [ $? -ne 0 ]; then
  echo "go test coverage fail" >&2
  exit 1
fi

goveralls -coverprofile=coverage.out -service=travis-ci

if [ $? -ne 0 ]; then
  echo "go update test coverage fail" >&2
  exit 1
fi

exit 0
